/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * 라이브러리를 사용할 때 Shared Library를 불러올 수 있도록 수정되었습니다.
 * ----------------------------------------------------------------------------- */

package org.chasen.mecab;

import java.io.File;

public class MeCab implements MeCabConstants {
    public static synchronized void initialize(String osName) {
        System.out.println("Loading MeCab library...");
        String targetFolder = "/lib";
        String libraryFileName = "libMeCab";
        if (osName.indexOf("Mac") >= 0) {
            System.out.println("Environment macOS detected.");
            libraryFileName += ".dylib";
        } else {
            System.out.println("Environment Linux detected.");
            libraryFileName = ".so";
        }
        
        File libraryFile = new File(targetFolder, libraryFileName);
        try {
            System.load(libraryFile.getAbsolutePath());
            System.out.println("MeCab was successfully loaded.");
        } catch (Exception e) {
            System.out.println("Exception was occurred while loading library file");
            e.printStackTrace();
            System.exit(1);
        }
    }
}
